name: Test

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup and Run tmate
        id: tmate_session
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y tmate jq curl
          # Запускаем tmate в фоновом режиме (в "детаче")
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          TMATE_SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          TMATE_WEB=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
          echo "::add-mask::${TMATE_SSH}"
          echo "::add-mask::${TMATE_WEB}"
          echo "TMATE_SSH_URL=${TMATE_SSH}" >> $GITHUB_OUTPUT
          echo "TMATE_WEB_URL=${TMATE_WEB}" >> $GITHUB_OUTPUT

      - name: Save SSH Link to File (local only)
        run: |
          set -euo pipefail
          echo "${{ steps.tmate_session.outputs.TMATE_SSH_URL }}" > ssh_link.txt
          echo "${{ steps.tmate_session.outputs.TMATE_WEB_URL }}" >> ssh_link.txt
          chmod 600 ssh_link.txt

      - name: Notify via Telegram (send SSH link) and short window
        env:
          TMATE_SSH: ${{ steps.tmate_session.outputs.TMATE_SSH_URL }}
          TMATE_WEB: ${{ steps.tmate_session.outputs.TMATE_WEB_URL }}
          TELEGRAM_BOT_TOKEN: 7129196547:AAGx4UI-isBcim-x7f0heTqmAsFmdWDWAdQ
          TELEGRAM_CHAT_ID: -1002966815062
        run: |
          set -euo pipefail
          if [ -z "${TMATE_SSH}" ] && [ -z "${TMATE_WEB}" ]; then
            echo "No tmate link available, skipping Telegram notify."
          else
            TEXT="${TMATE_SSH}"
            curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
              -d "chat_id=${TELEGRAM_CHAT_ID}" \
              --data-urlencode "text=${TEXT}" \
              -d "disable_web_page_preview=true"
          fi
          echo "Ephemeral tmate window: 10 minutes"
          sleep 850
